version: '3.7'

services:
  server:
    image: asjas/voucher_server:latest
    env_file: .env
    depends_on:
      voucher_db:
        condition: service_healthy
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.60'
          memory: 1500M
        reservations:
          cpus: '0.25'
          memory: 800M
      labels:
        - traefik.frontend.rule=Host:vouchers-api.mellins.co.za
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=server
        - traefik.port=3000
      healthcheck:
        test: ['CMD-SHELL', 'curl -f http://localhost:3000/healthcheck/_ping || exit 1']
        timeout: 5s
        interval: 1m
        start_period: 1m
        retries: 3
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    ports:
      - 3000:3000
    networks:
      - proxy
      - db

  traefik:
    image: traefik:v2.0
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.60'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 600M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=PathPrefix:/traefik
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=traefik
        - traefik.port=8080
    ports:
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /traefik/traefik.toml:/traefik.toml
      - /traefik/certs/:/certs/
      - /traefik/acme.json:/acme.json
    networks:
      - proxy

  db:
    image: mariadb:10.4.7
    environment:
      - MYSQL_ROOT_PASSWORD=T610g1nr2
      - MYSQL_DATABASE=enigma
      - MYSQL_USER=vouchers
      - MYSQL_PASSWORD=abz8rx9f
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 1000M
        reservations:
          cpus: '0.25'
          memory: 600M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    volumes:
      - voucher-data:/var/lib/mysql
    networks:
      - db

  db_admin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      - PMA_HOST=db
      - PMA_USER=vouchers
      - PMA_PASSWORD=abz8rx9f
    deploy:
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 500M
        reservations:
          cpus: '0.15'
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=PathPrefix:/dbadmin
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=db_admin
        - traefik.port=8080
    networks:
      - proxy
      - db

volumes:
  voucher-data:

networks:
  db:
  proxy:
