version: '3.7'

services:
  server:
    image: asjas/voucher_server:v1.0.9
    depends_on:
      - voucher_db
    deploy:
      replicas: 1
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
      labels:
        - traefik.frontend.rule=Host:vouchers-api.mellins.co.za
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=server
        - traefik.port=3000
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    ports:
      - 3000:3000
    networks:
      - proxy
      - db

  traefik:
    image: traefik
    deploy:
      replicas: 1
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=PathPrefix:/traefik
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=traefik
        - traefik.port=8080
    ports:
      - '443:443'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/mellins-enigma-vouchers/traefik/traefik.toml:/traefik.toml
      - /root/mellins-enigma-vouchers/traefik/certs/:/certs/
      - /root/mellins-enigma-vouchers/traefik/acme.json:/acme.json
    networks:
      - proxy

  db:
    image: mariadb:10.4.7
    environment:
      - MYSQL_ROOT_PASSWORD=T610g1nr2
      - MYSQL_DATABASE=enigma
      - MYSQL_USER=vouchers
      - MYSQL_PASSWORD=abz8rx9f
    deploy:
      replicas: 1
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
    volumes:
      - voucher-data:/var/lib/mysql
    networks:
      - db

  db_admin:
    image: phpmyadmin/phpmyadmin:4.9
    environment:
      - PMA_HOST=db
      - PMA_USER=vouchers
      - PMA_PASSWORD=abz8rx9f
    deploy:
      replicas: 1
      update_config:
        delay: 5s
        failure_action: rollback
        max_failure_ratio: .5
        monitor: 10s
        parallelism: 1
      resources:
        limits:
          cpus: '0.20'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s
      labels:
        - traefik.frontend.rule=PathPrefix:/dbadmin
        - traefik.enable=true
        - traefik.protocol=http
        - traefik.backend=db_admin
        - traefik.port=8080
    networks:
      - proxy
      - db

volumes:
  voucher-data:

networks:
  db:
  proxy:
