debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
domain = "mellins.co.za"
swarmMode = true
swarmModeRefreshSeconds = 15
network = "vouchers_proxy"
exposedByDefault = false

[api]
entrypoint = "traefik"
dashboard = true
debug = true
